### PR TITLE
iterators that return move-only types by value should satisfy Readable

### PR DESCRIPTION
**Pull request by ericniebler**

### CODE REVIEW

**Comment by ericniebler** [comment]
See ericniebler/stl2#399

**Comment by ericniebler** [comment]
Appveyor looks busted for cmcstl2.

**Comment by CaseyCarter** [comment]
> Appveyor looks busted for cmcstl2.

WTF, how did Appveyor get enabled for this repo?!?

**Comment by ericniebler** [comment]
Don't ask me.

**Pull request merged**
